version: '3.8'
services:
# it is the database services which we create here
  vprodb:
    build:
      context: ./Docker-files/db
    image: manas2002goyal/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

# this is the memcache 
  vprocache01 :
    image: memcached
    ports:
      - "11211:11211"

  # this is the rabbitmq
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

# this is the main application
  vproapp:
    build:
      context: ./Docker-files/app
    image: manas2002goyal/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"

# this is the nginx
  vproweb:
    build:
      context: ./Docker-files/web
    image: manas2002goyal/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"

# this is used to define your volumes
volumes:
  vprodbdata: {}
